name: deploy

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # - name: Test
      #   run: go test -race ./...

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -ldflags "-X github.com/ykstudy/stock/version.Version=`TZ=Asia/Shanghai date +'%y%m%d%H%M'`" -o app

      - name: Tar
        run: sed -i "s/env = \"localhost\"/env = \"prod\"/g" config.toml && tar czvf app.tar.gz app config.toml

      - name: SCP Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'app.tar.gz'
          target: ${{ secrets.REMOTE_TARGET }}

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: ${{ secrets.AFTER_COMMAND }}
